### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by ms-ufad** [xinwen-cs/AudioDVP#11]
Hello, can you provide a pre training model?Hello, can you provide a pre training model? Want to see other specific effects, baidu cloud link what do you have?

**Comment by chensheng-code** [comment]
Is it convenient to talk about your training data set?

**Comment by ms-ufad** [comment]
In the\ demo.sh Is this the whole training and testing process?

**Comment by xinwen-cs** [comment]
We've provide both training and testing code. So we won't distribute trained model due to legal concerns :)
You need to train by yourself (It takes several hours).
