### ISSUE TITLE
triangles must be contiguous

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#12]
RuntimeError: triangles.is_contiguous() INTERNAL ASSERT FAILED at rasterize_triangles.cpp:47, please report a bug to PyTorch. triangles must be contiguous

I meet this problem,do you know how to solve it?
thanks.

**Comment by ghost** [comment]
when I run ./scripts/demo.sh in this step:

# # # 3D face reconstruction
     python train.py \
    --data_dir $video_dir \
    --num_epoch 20 \
    --serial_batches False \
    --display_freq 400 \
    --print_freq 400 \
    --batch_size 5

error:

  File "/AudioDVP_master/renderer/rasterizer.py", line 21, in forward
    px_triangle_ids, px_barycentric_coords, z_buffer = rasterize_triangles_cpp.forward(vertices, triangles, image_width, image_height,px_triangle_ids, px_barycentric_co
RuntimeError: triangles.is_contiguous() INTERNAL ASSERT FAILED at rasterize_triangles.cpp:47, please report a bug to PyTorch. triangles must be contiguous

**Comment by darkcorvushhh** [comment]
I also met this problem, did you find the solution? thanks a lot

**Comment by xinwen-cs** [comment]
I think PyTorch version counts. PyTorch 1.0-1.2 is ok as far as I know.
Feel free to reopen this issue :)
