### ISSUE TITLE
loss is right?

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#13]
loss is right?

Alpha and Beta is becoming bigger.

(epoch: 0, iters: 400, data: 4.051, comp: 0.276) Photometric: 0.00181 Landmark: 7718.11133 Alpha: 0.05172 Beta: 0.29063 Delta: 61.63796
(epoch: 0, iters: 800, data: 0.080, comp: 0.192) Photometric: 0.00146 Landmark: 967.15063 Alpha: 0.13425 Beta: 1.17731 Delta: 63.90876
(epoch: 0, iters: 1200, data: 0.002, comp: 0.204) Photometric: 0.00158 Landmark: 1975.64294 Alpha: 0.23449 Beta: 2.57856 Delta: 73.03019
(epoch: 0, iters: 1600, data: 0.086, comp: 0.196) Photometric: 0.00150 Landmark: 1680.22449 Alpha: 0.35264 Beta: 4.44597 Delta: 82.82761
(epoch: 0, iters: 2000, data: 2.022, comp: 0.212) Photometric: 0.00152 Landmark: 1176.67371 Alpha: 0.45922 Beta: 6.69235 Delta: 94.46399
(epoch: 0, iters: 2400, data: 0.083, comp: 0.216) Photometric: 0.00128 Landmark: 791.45978 Alpha: 0.57932 Beta: 9.26394 Delta: 85.35516
(epoch: 0, iters: 2800, data: 0.079, comp: 0.205) Photometric: 0.00131 Landmark: 865.98560 Alpha: 0.72245 Beta: 12.09630 Delta: 60.82056
(epoch: 0, iters: 3200, data: 0.080, comp: 0.202) Photometric: 0.00135 Landmark: 1978.97888 Alpha: 0.87332 Beta: 15.07739 Delta: 72.84588
(epoch: 0, iters: 3600, data: 0.085, comp: 0.199) Photometric: 0.00130 Landmark: 742.81793 Alpha: 1.04230 Beta: 18.29398 Delta: 76.42062
(epoch: 0, iters: 4000, data: 0.090, comp: 0.197) Photometric: 0.00113 Landmark: 585.40186 Alpha: 1.20340 Beta: 21.58375 Delta: 63.59510
(epoch: 0, iters: 4400, data: 1.558, comp: 0.204) Photometric: 0.00110 Landmark: 670.62146 Alpha: 1.38092 Beta: 24.90604 Delta: 65.81146
(epoch: 0, iters: 4800, data: 0.002, comp: 0.198) Photometric: 0.00108 Landmark: 731.14294 Alpha: 1.56694 Beta: 28.31109 Delta: 67.26335
(epoch: 0, iters: 5200, data: 0.080, comp: 0.205) Photometric: 0.00103 Landmark: 902.36053 Alpha: 1.75208 Beta: 31.82484 Delta: 60.93861
(epoch: 0, iters: 5600, data: 0.002, comp: 0.205) Photometric: 0.00111 Landmark: 708.53540 Alpha: 1.99122 Beta: 35.27546 Delta: 60.29773
(epoch: 0, iters: 6000, data: 0.080, comp: 0.209) Photometric: 0.00123 Landmark: 892.47137 Alpha: 2.17174 Beta: 38.81593 Delta: 46.08813

**Comment by xinwen-cs** [comment]
Alpha and Beta is regularization, not loss. It seems ok, you can check output video after fitting.
