### ISSUE TITLE
how to train with chinese?

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#14]
how to train with chinese? not english.

**Comment by ghost** [comment]
German Speech Results. Although the high-dimensional feature
extraction from audio in our Audio2Expression network is only trained
on an English corpus, it generalizes to some other languages, such as
German.

so how to train with chinese language of Audio2Expression network?

**Comment by xinwen-cs** [comment]
English and German have similar alphabet, so it can works. For Chinese, you need to use a big audio-video corpus to train from scratch:)

**Comment by ghost** [comment]
how to use a big audio-video corpus to train from scratch in detail? 
the code and method.

**Comment by ghost** [comment]
@xinwen-cs
