### ISSUE TITLE
how to increase the size of output video ?

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#15]
output video size= 256*256
how to increase the size of output video ?

**Comment by ghost** [comment]
I want to get the output video size which is same as the input size.(such as 1920*1080)

**Comment by xinwen-cs** [comment]
The output size of the generator is fixed at 256 by 256.
You can use larger network. And you don't have to use 1920*1080 because face region is way smaller than it.
You can crop face region and paste the output back to original video as we've done in the paper.

**Comment by ghost** [comment]
具体怎么做？谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xinwen-cs"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 下午3:14
收件人: "xinwen-cs/AudioDVP"<AudioDVP@noreply.github.com&gt;; 
抄送: "陈柏霖"<2549853330@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xinwen-cs/AudioDVP] how to increase the size of output video ? (#15)





 
发生器的输出大小固定为256 x256 
 。可以使用更大的网络。而且您不必使用1920 * 1080，因为面部区域远小于它。
 您可以裁剪面部区域，然后将输出粘贴回原始视频中，就像我们在本文中所做的那样。
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by xinwen-cs** [comment]
这个功能已经实现了, 我们使用的youtube视频都是大于等于1080p的.

**Comment by ghost** [comment]
但是我想输出人物占图像的比重与输入人物占图像的比重是一样大的，这个怎么处理？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xinwen-cs"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 下午3:20
收件人: "xinwen-cs/AudioDVP"<AudioDVP@noreply.github.com&gt;; 
抄送: "陈柏霖"<2549853330@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xinwen-cs/AudioDVP] how to increase the size of output video ? (#15)





 
这个功能已经实现了, 我们使用的youtube视频都是大于等于1080p的.

**Comment by xinwen-cs** [comment]
I don't have good suggestion. I think it is not neccesary.

**Comment by ghost** [comment]
输出视频的人物脸部 与 输入视频的人物脸部 不同大小，还是想输入输出一样的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xinwen-cs"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 下午3:26
收件人: "xinwen-cs/AudioDVP"<AudioDVP@noreply.github.com&gt;; 
抄送: "陈柏霖"<2549853330@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xinwen-cs/AudioDVP] how to increase the size of output video ? (#15)





 
我没有很好的建议。我认为这不是必需的。
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
