### ISSUE TITLE
why the people not in the center of the picture ?

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#16]
![epoch001_fake_B](https://user-images.githubusercontent.com/40932226/105809017-dcb50d80-5fe3-11eb-83e8-7cd9dc4c7707.png)

why the people not in the center of the picture ?

**Comment by xinwen-cs** [comment]
You need to adjust this [parameter](https://github.com/xinwen-cs/AudioDVP/blob/c3829b9f1056827e2fe8b2d1fc9083c8cba93984/utils/crop_portrait.py#L66) mannually if not cropped well.
Now the pipeline is not fully automatic, pull request is wellcomed.
