### ISSUE TITLE
./scripts/demo.sh: 行 104: 30820 已杀死     会爆内存

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#17]
./scripts/demo.sh: 行 104: 30820 已杀死     会爆内存，应该在哪部降低内存呢？

./scripts/demo.sh: 行 104: 30820 已杀死               /home/chenbl/anaconda3/envs/cbl/bin/python3 vendor/neural-face-renderer/train.py --dataroot $video_dir/nfr/AB --name fr --model nfr --checkpoints_dir $video_dir/checkpoints --netG unet_256 --direction BtoA --lambda_L1 100 --dataset_mode temporal --norm batch --pool_size 0 --use_refine --nput_nc 21 --Nw 7 --batch_size 8 --preprocess none --num_threads 4 --n_epochs 6 --n_epochs_decay 0 --load_size 256

**Comment by ghost** [comment]
你是一次性读取全部图像了吧？怎么改为每次只读取一部分数据呢？

**Comment by xinwen-cs** [comment]
I think it is feasible and not hard but a little bit troublesome. You can try it freely.
