### ISSUE TITLE
why the mask is bigger?

### ISSUE THREAD

**Issue by ghost** [xinwen-cs/AudioDVP#18]
why the mask is bigger?   
--crop_level 4 \    --vertical_adjust 0.1

![aa](https://user-images.githubusercontent.com/40932226/106733872-5b95f000-664d-11eb-9d65-070a5293fa99.PNG)

**Comment by xinwen-cs** [comment]
I think face reconstruction stage is not functioning well. Check debug output. Maybe the detected landmark is wrong.
