### ISSUE TITLE
RuntimeError: triangles.is_contiguous() INTERNAL ASSERT FAILED at "rasterize_triangles.cpp"

### ISSUE THREAD

**Issue by iamchenxin-coder** [xinwen-cs/AudioDVP#23]
This error occurs when I run the train.py script. I don't know how to fix it.
python **train.py** --data_dir $video_dir --num_epoch 20 --serial_batches False --display_freq 400 --print_freq 400 --batch_size 5

![image](https://user-images.githubusercontent.com/74162528/113127656-9716fa00-924b-11eb-9eb5-db0220e55626.png)

![image](https://user-images.githubusercontent.com/74162528/113127615-8a92a180-924b-11eb-82be-1c2c1d048e1f.png)

**Comment by RylanLiu-buaa** [comment]
之前用pytorch1.2和NVIDIA 1070就能通跑20s数据量的，但跑作者给的240s的就会显存不够。所以换成NVIDIA 3090，但需要pytorch1.8 这3090才能工作，但就会出上面这个triangles的错误。pytorch1.2 3090卡是不工作的直接程序就卡死在那了。估计就是pytorch的版本问题。

**Comment by iamchenxin-coder** [comment]
我使用Tesla V100的torch=1.8还是出现这个问题

**Comment by quqixun** [comment]
在 renderer/rasterizer.py 文件第19行前加入以下两行：
```python
if not triangles.is_contiguous():
    triangles = triangles.contiguous()
```
测试环境为 Pytorch 1.8 + CUDA 11.1。

**Comment by 425776024** [comment]
> Pytorch 1.8 + CUDA 11.1

我Pytorch 1.8 + CUDA 11.1编译不了`python setup.py build_ext --inplace` 不知道为什么？

**Comment by xinwen-cs** [comment]
@quqixun thanks for PR
seems solved
