### ISSUE TITLE
run reenact.py error

### ISSUE THREAD

**Issue by iamchenxin-coder** [xinwen-cs/AudioDVP#25]
运行文件**python** reenact.py --src_dir $audio_dir --tgt_dir $video_dir时出现下面的错误，我的torch版本是1.1.0-1.2.0
![image](https://user-images.githubusercontent.com/74162528/113833119-db5e4900-97bb-11eb-821d-66f0bbe5c39c.png)

![image](https://user-images.githubusercontent.com/74162528/113832948-ace06e00-97bb-11eb-8d99-8857dec39c7b.png)

当我将torch版本增加到1.4和1.5时出现：
![image](https://user-images.githubusercontent.com/74162528/113833379-2a0be300-97bc-11eb-8116-4766cd941250.png)

当我将torch版本增加到1.6以上时出现：
![image](https://user-images.githubusercontent.com/74162528/113833248-02b51600-97bc-11eb-8da2-e2a97ac14c62.png)

**麻烦问下作者，这个问题怎么解决？**

**Comment by xinwen-cs** [comment]
可能是00001.pt结构坏掉了,可以重新跑一下,或者用00002.pt替换掉
