### ISSUE TITLE
训练神经网络人脸渲染器会在某个epoch卡死

### ISSUE THREAD

**Issue by RylanLiu-buaa** [xinwen-cs/AudioDVP#28]
在运行下面这步时，使用设置时长为240s，运行到某个epoch就卡死不动了，没有任何的输出，GPU占用率为0%，这是什么问题呢？
# # train neural face renderer # python vendor/neural-face-renderer/train.py  #     --dataroot $video_dir/nfr/AB --name nfr --model nfr --checkpoints_dir $video_dir/checkpoints \ #     --netG unet_256 --direction BtoA --lambda_L1 100 --dataset_mode temporal --norm batch --pool_size 0 --use_refine \ #     --input_nc 21 --Nw 7 --batch_size 16 --preprocess none --num_threads 4 --n_epochs 250 \ #     --n_epochs_decay 0 --load_size 256
没有办法完全跑完250个epoch，有时候在epoch=26的时候或者在epoch=19的时候命令行就停在那里不动了，也不报任何错误，不再继续输出。会不会跟visdom那个库有关系。终止再重新运行的时候就会卡在 “开始一个session”那句输出上，只能关了命令行重新运行，这是什么问题呢？使用时长为20s时候由于数据量小就不会有这问题。

**Comment by xinwen-cs** [comment]
是和visdom有关,有概率卡住
