### ISSUE TITLE
本地Tesla V100推理时间和论文GTX 2080 ti进行推理的时间相差太大

### ISSUE THREAD

**Issue by iamchenxin-coder** [xinwen-cs/AudioDVP#29]
作者你好，我在本地使用V100进行推理，其中输入音频是16s，生成的视频是16s * 25frame = 400frame，以下是推理的比较，请教一下作者为什么我实际的推理时间和论文的差距这么大呢？存在什么问题吗？
![image](https://user-images.githubusercontent.com/74162528/115396983-2777a780-a218-11eb-97ae-ab34e2bf5ecb.png)

**Comment by iamchenxin-coder** [comment]
作者请问能留一个联系方式吗

**Comment by junleen** [comment]
我也觉得作者给的渲染时间太短了，除非全部是C++写的

**Comment by 821029883** [comment]
同学您好，我们最近也在从事相似的内容，可否加个联系方式一同探讨：chat/QQ: 821029883

**Comment by iamchenxin-coder** [comment]
OK

**Comment by xinwen-cs** [comment]
论文中计算时间没有包含磁盘io部分, 望周知

**Comment by piwawa** [comment]
作者论文哪里提出推理速度数据了？找了半天没找到
