### ISSUE TITLE
can not find 'python_speech_features' module

### ISSUE THREAD

**Issue by eudoraxj** [xinwen-cs/AudioDVP#3]
ModuleNotFoundError: No module named 'python_speech_features'

where's the python_speech_features file

**Comment by xinwen-cs** [comment]
It is a Python Package. You need to install it through pip or conda.
`pip install python-speech-features==0.6`
If you  encounter other missing packages, you need to check [my environment](https://github.com/xinwen-cs/AudioDVP/blob/master/enviroment.yml)
