### ISSUE TITLE
论文中没有提到输入测试音频的采样率和目标视频的采样率必须一致

### ISSUE THREAD

**Issue by iamchenxin-coder** [xinwen-cs/AudioDVP#30]
作者你好，我想问一下，你们在实际测试的过程中测试音频的采样率和目标视频的采样率，如果不一样，你们做了什么处理？我在实际中发现，当输入的测试音频的采样率和目标视频的采样率不一样，最后生成的视频的嘴型是有部分对不上的，请问下这个问题你们有考虑过吗？

**Comment by xinwen-cs** [comment]
代码中有写,音频输入会按照16k采样率统一处理
