### ISSUE TITLE
关于Audio2expression模型相关求助

### ISSUE THREAD

**Issue by 821029883** [xinwen-cs/AudioDVP#31]
作者您好，感谢您开源的相关代码。
留意到您的Audio2expression模型仅使用3个卷积+一个全连接，
我们在tensorboard上观察loss下降至3e-3左右，我们使用之进行推理发现存在相关问题：
1.嘴唇变化幅度较小
2.人物嘴唇存在抖动情况(类似于打哆嗦)
我们尝试修改Audio2expression(增加全连接层数量，增大batch_size)可让loss降低至1.5e-4，
但是我们发现其表现效果更差了(哆嗦情况加重，反复抖动)
您是否有比较好的意见或者建议呢？
感谢！

**Comment by 821029883** [comment]
如果可以，可否加个联系方式，wechat/QQ: 821029883

**Comment by NingNanXin** [comment]
> 如果可以，可否加个联系方式，wechat/QQ: 821029883

请问你解决了这个问题吗，我尝试了作者说的Lip Reading Sentences in the Wild，自己又改了一个小的transformer，但是抖动比作者的代码都要严重
