### ISSUE TITLE
如何训练中文数据集？

### ISSUE THREAD

**Issue by Adorablepet** [xinwen-cs/AudioDVP#32]
非常感谢您分享这样的一个工程，非常棒。关于训练中文数据集，我有几点想法，如下：
![image](https://user-images.githubusercontent.com/29625016/117912574-52828200-b312-11eb-95ff-18c022df72f8.png)
如果有问题或者意见，希望您可以提出，中文数据集有参考的吗？谢谢。

**Comment by 821029883** [comment]
我们目前的想法和您比较一致，想实现在中文数据集上面的良好嘴唇同步。
基本思路也是主要修改ATVG-net的AT-net预先训练权重（我们爬取了CCTV数据集进行训练），而后使用AT-net提取音频高层次特征，
在目标视频上fine-tune Audio-->expression模型，但是表现效果不佳（甚至不如作者提供的AT-net权重，嘴唇基本不怎么动）。
可否加个联系方式，大家共同探讨呢，wechat/QQ:821029883

**Comment by Adorablepet** [comment]
@821029883 其实在很早之前我就用中文数据集（自己爬虫）训练过ATVGnet网络，效果和你的情况一样，嘴唇基本不怎么动，后来就放弃啦，在项目下也提过issue，好像作者也没有正面回答。

**Comment by xinwen-cs** [comment]
方法中采用的音频特征提取网络是用英文训练的,迁移到中文上效果不好是符合预期的,建议train from scratch
