### ISSUE TITLE
黑点

### ISSUE THREAD

**Issue by 425776024** [xinwen-cs/AudioDVP#34]
作者你好，我合成的视频发现每1-2s左右就产生带黑点的画面，而且不是纯黑的点

**Comment by xinwen-cs** [comment]
代码里的mesh renderer有bug，渲染得到的三维模型是有黑点的。
但是gan的输出产生黑点的问题，我没遇到过，检查一下gan的输入是不是也有黑点

**Comment by 425776024** [comment]
GAN的输入是render的图像，看了是有部分有黑点，大概占比1/20，翻译后的人脸图像也大概这么多有黑点
![image](https://user-images.githubusercontent.com/14906671/131621778-f90f1c26-06c6-4203-aa58-48aadb753bc0.png)

**Comment by FusionLi** [comment]
@425776024 你好，我也遇到类似问题了，请问你找到原因了吗？

**Comment by 425776024** [comment]
> @425776024 你好，我也遇到类似问题了，请问你找到原因了吗？

加了随机送种子，pix2pix训练数据前置准备尽量做的好一些，不要训练太多轮，delta值用torch. clamp剪切到正常范围。
