### ISSUE TITLE
.

### ISSUE THREAD

**Issue by zg734** [xinwen-cs/AudioDVP#36]
.

**Comment by ypisarchik** [comment]
For example on my current run it happened during the second epoch of training:
(epoch: 2, iters: 200, data: 0.034, comp: 0.085) Photometric: 0.00160 Landmark: 1012.80090 Alpha: 1.88417 Beta: 6.81392 Delta: 351.86545
(epoch: 2, iters: 600, data: 0.034, comp: 0.548) Photometric: nan Landmark: nan Alpha: nan Beta: nan Delta: nan
