### ISSUE TITLE
./scripts/merge_frames.sh not found

### ISSUE THREAD

**Issue by qianxinchun** [xinwen-cs/AudioDVP#4]
In train.py, 
`os.system("./scripts/merge_frames.sh %s" % opt.data_dir)`
but merge_frames.sh not found.

**Comment by xinwen-cs** [comment]
Sorry, I forget to remove this line of code. This script is for face reconstruction debugging.
I have uploaded `merge_frames.sh`. Or you can just ignore this line of code.

**Comment by xinwen-cs** [comment]
You can just ignore this line. The `merge_frames.sh` is embedded in `demo.sh` :)
