### ISSUE TITLE
The actual test results of others are different from those in the paper

### ISSUE THREAD

**Issue by Arthurzhangsheng** [xinwen-cs/AudioDVP#40]
![image](https://user-images.githubusercontent.com/33758384/211237154-2f15f083-a110-4c9c-aa5e-80c6ae1a84f8.png)
在audioDVP论文里说是3分钟目标视频即可，但华为研究院测试说要10小时以上的数据才效果好
这个应该信谁的？

**Comment by huangzhengwang** [comment]
> ![image](https://user-images.githubusercontent.com/33758384/211237154-2f15f083-a110-4c9c-aa5e-80c6ae1a84f8.png) 在audioDVP论文里说是3分钟目标视频即可，但华为研究院测试说要10小时以上的数据才效果好 这个应该信谁的？

我3090跑作者的demo脚本，差不多要用几个小时，而且效果还没得他发出来的视频效果好，嘴巴有重影。
