### ISSUE TITLE
Could not find  the rasterize_triangles_cpp

### ISSUE THREAD

**Issue by doctorimage** [xinwen-cs/AudioDVP#6]
ERROR: Could not find a version that satisfies the requirement rasterize_triangles_cpp==0.0.0 (from versions: none)
ERROR: No matching distribution found for rasterize_triangles_cpp==0.0.0
try：
1）won't work to change all kinds of sources
2）won't work to delete "==0.0.0"

**Comment by eudoraxj** [comment]
I can't find this package either, how to install it?

**Comment by xinwen-cs** [comment]
See step 6.
You need to compile it.
