### ISSUE TITLE
Step: Crop and resize video frames too slow

### ISSUE THREAD

**Issue by House-Leo** [xinwen-cs/AudioDVP#7]
# crop and resize video frames
# python utils/crop_portrait.py \
#    --data_dir $video_dir \
#    --crop_level 2.0 \
#    --vertical_adjust 0.2
![image](https://user-images.githubusercontent.com/47940711/99647018-2d603580-2a8c-11eb-95d6-cb07a23ff1a1.png)

Do you have the same problem? Or is it have to be slow?

**Comment by xinwen-cs** [comment]
It is a little bit slow on my machine, but not that much like yours. Check main memory usage first.

**Comment by House-Leo** [comment]
> It is a little bit slow on my machine, but not that much like yours. Check main memory usage first.

It seems that will cost about 20 hours to preprocess.

**Comment by House-Leo** [comment]
![image](https://user-images.githubusercontent.com/47940711/99659906-8b951480-2a9c-11eb-8e10-7850865c8a0b.png)


> It is a little bit slow on my machine, but not that much like yours. Check main memory usage first.

**Comment by House-Leo** [comment]
I have solved it . Don't use pip install dlib. Need to install dlib from source code.

**Comment by wayneszq** [comment]
> I have solved it . Don't use pip install dlib. Need to install dlib from source code.

Hi any suggestion for install dilib?  I installed from souce code like the following:
`git clone https://github.com/davisking/dlib.git
cd dlib
mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1; cmake --build .
cd ..
python setup.py install`

Still got it very slow. Any suggestion? thanks.

dlib: version: 19.21.99
face_recognition  version 1.3.0

**Comment by House-Leo** [comment]
> > I have solved it . Don't use pip install dlib. Need to install dlib from source code.
> 
> Hi any suggestion for install dilib? I installed from souce code like the following:
> `git clone https://github.com/davisking/dlib.git cd dlib mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1; cmake --build . cd .. python setup.py install`
> 
> Still got it very slow. Any suggestion? thanks.
> 
> dlib: version: 19.21.99
> face_recognition version 1.3.0

Please follow [https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf](url)
`git clone https://github.com/davisking/dlib.git`
`cd ..
python3 setup.py install`
And test it after installing. Follow `python` `import dlib` `dlib.DLIB_USE_CUDA` , and the output you get is True.
